name: tigergraph-ml
channels:
  - pyg
  - pytorch
  - conda-forge
dependencies:
  - conda
  - cudatoolkit-dev=11.0
  - matplotlib-base
  - numpy
  - pandas
  - pip
  - python=3.9
  - scipy
  - jq
  - pytorch
  - pyg
  - jupyterlab-git
  - jupyterlab_code_formatter
  - black
  - isort
  - pip:
    - pyTigerGraph
    - tgml[pyg]
    - tensorboard